[www]
user = www-data
group = www-data

listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 50       ; total simultaneous PHP-FPM workers
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 500       ; recycle workers to avoid memory leaks

; Enable FPM status and ping endpoints
pm.status_path = /status
ping.path = /ping

; Optional: allow only certain clients (NGINX container)
; listen.allowed_clients = 172.19.0.0/16

